export const menuItems = [
  {
    key: 'master',
    name: 'Master Data - Business',
    route: '/document',
    icon: '',
    isPin: false,
  },
  {
    key: 'product',
    name: 'Master Data - Product',
    route: '#',
    icon: '',
    isPin: false,
  },
  {
    key: 'orderBom',
    name: 'Master Data Maintanane',
    route: '#',
    icon: '',
    isPin: false,
  },
  {
    key: 'purchasing',
    name: 'Service Management',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },
  {
    key: 'sourcing',
    name: 'Billing',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },
  {
    key: 'engDiscrete',
    name: 'Accounts Receivable',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },
  {
    key: 'engProcess',
    name: 'Cridit Management',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },
  {
    key: 'admin',
    name: 'Administration',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },
  {
    key: 'docu',
    name: 'Document Management',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },
  {
    key: 'purch',
    name: 'Purchasing',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },

  {
    key: 'bom',
    name: 'Order BOM Management',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },

  {
    key: 'software',
    name: 'Software Constraints',
    route: '#',
    icon: 'fa-chevron-down',
    isPin: false,
  },
];

export const questions = [
  'Find Help',
  'Entry Page',
  'Notifications',
  'User Actions Menu',
  'Built-in Support',
  'To Dos',
  'Pages',
  'Apps and Activities',
  'Insights',
];
